# Generated by Django 5.2.17 on 2026-08-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_table',
        ),
    ]
