# Generated by Django 5.2.17 on 2026-08-28 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_training_program_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_session',
            name='date_added',
        ),
        migrations.AddField(
            model_name='training_session',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training_session',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
