# Generated by Django 5.2.17 on 2026-08-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_training_session_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_session',
            name='title',
        ),
    ]
