# Generated by Django 5.2.17 on 2026-08-12 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_session',
            name='user',
        ),
        migrations.AddField(
            model_name='training_program',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.user'),
        ),
    ]
