# Generated by Django 5.2.17 on 2026-08-28 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_training_session_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_session',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
